from uploads.file_handler import S3_BUCKET_NAME


AWS_ACCESS_KEY = 'ADD_YOUR_KEY_HERE'
AWS_SECRET_KEY = 'ADD_YOUR_KEY_HERE'
AWS_REGION = 'ADD_YOUR_REGION_HERE'
S3_BUCKET_NAME = 'ADD_YOUR_BUCKET_NAME_HERE'